version: '3.4'
services:
  db:
    image: vinymt/mysql-estados-api
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 0602abn12479vgs56962bvg
      MYSQL_USER: docker
      MYSQL_PASSWORD: 0602abn12479vgs56962bvg
      MYSQL_DATABASE: states_and_regions
    ports:
      - "3308:3306"
    networks:
      - network1
  estados-API:
    image: vinymt/estados-api
    restart: always
    build: ./estados-API
    working_dir: /estados-API
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONENT: Production
    volumes:
      - ./estados-API:/estados-API
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - network1
networks:
    network1:
        driver: bridge